apiVersion: v1
kind: ConfigMap
metadata:
  name: maas-bin
data:
  start.sh: |
{{ tuple "bin/_start.sh.tpl" . | include "template" | indent 4 }}
  maas-region-controller.postinst: |
{{ tuple "bin/_maas-region-controller.postinst.tpl" . | include "template" | indent 4 }}
  import-boot-resources.sh: |
{{ tuple "bin/_import-boot-resources.sh.tpl" . | include "template" | indent 4 }}
  job-readiness.sh: |
{{ tuple "bin/_job-readiness.sh.tpl" . | include "template" | indent 4 }}
  register-rack-controller.sh: |
{{ tuple "bin/_register-rack-controller.sh.tpl" . | include "template" | indent 4 }}
