apiVersion: v1
kind: Secret
metadata:
  name: gnocchi-db-root
type: Opaque
data:
  DB_CONNECTION: {{ tuple "oslo_db" "internal" "admin" "postgresql" . | include "helm-toolkit.authenticated_endpoint_uri_lookup" | b64enc }}
